export const TOPICS_RETRIEVE_PENDING = "TOPICS_RETRIEVE_PENDING";
export const TOPICS_RETRIEVE_SUCCESS = "TOPICS_RETRIEVE_SUCCESS";
export const TOPICS_RETRIEVE_ERROR = "TOPICS_RETRIEVE_ERROR";

export const POSTS_RETRIEVE_PENDING = "POSTS_RETRIEVE_PENDING";
export const POSTS_RETRIEVE_SUCCESS = "POSTS_RETRIEVE_SUCCESS";
export const POSTS_RETRIEVE_ERROR = "POSTS_RETRIEVE_ERROR";

export const POST_CREATE_PENDING = "POST_CREATE_PENDING";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_ERROR = "POST_CREATE_ERROR";
