export const TOPICS_RETRIEVE_PENDING = "TOPICS_RETRIEVE_PENDING";
export const TOPICS_RETRIEVE_SUCCESS = "TOPICS_RETRIEVE_SUCCESS";
export const TOPICS_RETRIEVE_ERROR = "TOPICS_RETRIEVE_ERROR";
export const TOPICS_RESET = "TOPICS_RESET";

export const TOPIC_DETAILS_PENDING = "TOPIC_DETAILS_PENDING";
export const TOPIC_DETAILS_SUCCESS = "TOPIC_DETAILS_SUCCESS";
export const TOPIC_DETAILS_ERROR = "TOPIC_DETAILS_ERROR";
export const TOPIC_DETAILS_RESET = "TOPIC_DETAILS_RESET";

export const POSTS_RETRIEVE_PENDING = "POSTS_RETRIEVE_PENDING";
export const POSTS_RETRIEVE_SUCCESS = "POSTS_RETRIEVE_SUCCESS";
export const POSTS_RETRIEVE_ERROR = "POSTS_RETRIEVE_ERROR";
export const POSTS_RESET = "POSTS_RESET";

export const POST_CREATE_PENDING = "POST_CREATE_PENDING";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_ERROR = "POST_CREATE_ERROR";
