# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('forum.post',),
        ),
    ]
